"""
Distribution Agent — AI-Powered Distribution Copy Generator

Uses the existing Gemini AI provider to generate all distribution
text variants in a single API call:
    - Push notification title & body
    - Email subject & preview
    - RSS description
    - Daily digest summary
    - Future: Telegram/LinkedIn summaries
"""

import sys
import os
import json

# Add project root to path for AI provider access
_AUTOMATION_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _AUTOMATION_DIR not in sys.path:
    sys.path.insert(0, _AUTOMATION_DIR)


DISTRIBUTION_SYSTEM_PROMPT = """You are a distribution copy specialist for Mantbyte, a technical blog.

Given an article's title, excerpt, category, and URL, generate optimized copy for multiple distribution channels.

Rules:
- Keep push notification body under 100 characters
- Email subject should be compelling and under 60 characters
- RSS description should be informative, 1-2 sentences
- Digest summary should be concise, 1-2 sentences
- Do NOT use clickbait
- Maintain technical credibility
- Include relevant emoji in push notification title only

Respond in JSON format with exactly these keys:
{
    "push_title": "Push notification title (with emoji)",
    "push_body": "Push notification body (under 100 chars)",
    "email_subject": "Email subject line",
    "email_preview": "Email preview text (shown in inbox)",
    "rss_description": "RSS feed description",
    "digest_summary": "Summary for daily digest",
    "telegram_summary": "Future Telegram message",
    "linkedin_summary": "Future LinkedIn post"
}"""


def generate_distribution_assets(
    title: str,
    excerpt: str,
    category: str,
    url: str,
    cover_image: str = "",
) -> dict:
    """
    Generate all distribution copy variants via a single AI call.

    Args:
        title: Article title.
        excerpt: Article excerpt/summary.
        category: Article category (Tech, News, Geopolitics).
        url: Article URL.
        cover_image: Featured image URL.

    Returns:
        Dict with all distribution text variants.
        Falls back to sensible defaults if AI call fails.
    """
    try:
        from _ai.provider import generate_json

        user_prompt = f"""Generate distribution copy for this article:

Title: {title}
Category: {category}
Excerpt: {excerpt}
URL: {url}

Generate optimized copy for each distribution channel."""

        result = generate_json(
            agent_name="distribution_agent",
            system_instruction=DISTRIBUTION_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            temperature=0.4,
        )

        print(f"  🤖 Distribution assets generated by AI.")
        return result

    except Exception as e:
        print(f"  ⚠️ AI distribution agent failed ({e}). Using defaults.")
        return _fallback_assets(title, excerpt, category, url)


def _fallback_assets(title: str, excerpt: str, category: str, url: str) -> dict:
    """
    Generate distribution assets without AI.
    Used as fallback when the AI call fails.
    """
    # Truncate for push notification
    push_body = excerpt[:97] + "..." if len(excerpt) > 100 else excerpt

    return {
        "push_title": f"🚀 New on Mantbyte",
        "push_body": push_body,
        "email_subject": f"New Article: {title[:50]}",
        "email_preview": excerpt[:150],
        "rss_description": excerpt[:250],
        "digest_summary": excerpt[:200],
        "telegram_summary": f"📝 {title}\n\n{excerpt[:200]}\n\nRead more: {url}",
        "linkedin_summary": f"New article on Mantbyte: {title}\n\n{excerpt[:200]}",
    }
