"""
Mantbyte Distribution Engine — Main Orchestrator

This is the entry point for the Distribution Engine.
It reads the article event, dispatches to all enabled channels,
records notification history, and updates analytics.

Usage:
    python _automation/distribution/engine.py --event EVENT_JSON
    python _automation/distribution/engine.py [--test] [--digest]

Modes:
    --event:   Process an event JSON file generated by the distribution workflow
    --test:   Run with a mock event for testing
    --digest: Send the daily digest (called by cron)
"""

import sys
import os
import json
import argparse
import tempfile
from datetime import datetime

# Add _automation to path
AUTOMATION_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(AUTOMATION_DIR)
sys.path.insert(0, AUTOMATION_DIR)

from distribution.config import load_config
from distribution.analytics import AnalyticsTracker
from distribution.channels.base import ChannelInterface, DistributionResult


def _discover_channels(config: dict) -> list:
    """
    Auto-discover and instantiate all enabled channels.

    Each channel module in channels/ is imported and checked
    for ChannelInterface subclasses. Only enabled channels are returned.
    """
    channels = []

    # Import all channel implementations
    from distribution.channels.rss_validator import RSSValidatorChannel
    from distribution.channels.website_channel import WebsiteChannel
    from distribution.channels.push_channel import PushChannel
    from distribution.channels.newsletter_channel import NewsletterChannel
    from distribution.channels.digest_channel import DigestChannel

    # Instantiate and filter by enabled, IN EXACT REQUESTED ORDER:
    # 1. RSS
    # 2. Website Notification
    # 3. Push
    # 4. Newsletter
    # 5. Digest (not used for event-based publishing but discovered)
    all_channels = [
        RSSValidatorChannel(config),
        WebsiteChannel(config),
        PushChannel(config),
        NewsletterChannel(config),
        DigestChannel(config),
    ]

    for channel in all_channels:
        if channel.is_enabled(config):
            channels.append(channel)
            print(f"  ✅ Channel enabled: {channel.name}")
        else:
            print(f"  ⏭️ Channel disabled: {channel.name}")

    return channels


def _load_event(event_path: str) -> dict:
    """Load and validate the distribution event file."""
    if not os.path.exists(event_path):
        print(f"  ❌ Event file not found: {event_path}")
        return {}

    with open(event_path, "r") as f:
        event = json.load(f)

    if event.get("event") != "article_published":
        print(f"  ⚠️ Unknown event type: {event.get('event')}")
        return {}

    required_fields = ["title", "slug", "url"]
    for field in required_fields:
        if not event.get(field):
            print(f"  ❌ Event missing required field: {field}")
            return {}

    return event


def _check_duplicate(db, slug: str, channel: str) -> bool:
    """
    Check notification_history to prevent duplicate notifications.

    Returns True if this article+channel combo was already sent.
    """
    if not db:
        return False

    try:
        existing = (
            db.collection("notification_history")
            .where("article_id", "==", slug)
            .where("channel", "==", channel)
            .where("status", "in", ["success", "partial"])
            .limit(1)
            .get()
        )
        return len(list(existing)) > 0
    except Exception:
        return False


def _record_history(db, slug: str, result: DistributionResult):
    """Record distribution result in notification_history."""
    if not db:
        return

    try:
        db.collection("notification_history").add({
            "article_id": slug,
            "channel": result.channel,
            "status": result.status,
            "sent_at": datetime.utcnow().isoformat(),
            "delivery_count": result.sent_count,
            "failed_count": result.failed_count,
            "error": result.error,
            "details": result.details,
        })
    except Exception as e:
        print(f"  ⚠️ Failed to record history for {result.channel}: {e}")


def run_distribution(event_path: str = None):
    """
    Main distribution flow.

    1. Load config
    2. Load event
    3. Discover channels
    4. Dispatch to each channel (with duplicate prevention)
    5. Record history + analytics
    """
    print("\n" + "=" * 60)
    print("📡 MANTBYTE DISTRIBUTION ENGINE v1")
    print("=" * 60)

    # 1. Load config
    config = load_config()
    if getattr(args, 'dry_run', False):
        config['dry_run'] = True
        print("  🧪 DRY RUN MODE ENABLED - No real distributions will be sent.\n")
    else:
        print("  ✅ Configuration loaded.\n")

    # 2. Load the explicit temporary event generated by the workflow.
    if event_path is None:
        print("  ❌ No event path provided. Exiting.")
        return False

    event = _load_event(event_path)
    if not event:
        print("  ❌ No valid distribution event. Exiting.")
        return False

    slug = event.get("slug", "")
    print(f"  📄 Article: {event.get('title', 'Unknown')[:60]}")
    print(f"  🏷️ Category: {event.get('category', 'Unknown')}")
    print(f"  🔗 URL: {event.get('url', 'Unknown')}")
    print()

    # 3. Get Firestore (optional)
    db = None
    try:
        from distribution.channels.push_channel import get_firestore_db
        db = get_firestore_db(config)
    except Exception:
        print("  ⚠️ Firestore not available. History/analytics disabled.\n")

    # 4. Init analytics
    analytics = AnalyticsTracker(db)
    analytics.record_article_published()

    # 5. Discover and run channels
    channels = _discover_channels(config)
    print()

    results = []
    for channel in channels:
        print(f"  {'─' * 40}")
        print(f"  📡 Channel: {channel.name}")

        # Duplicate check
        if _check_duplicate(db, slug, channel.name):
            print(f"  ⏭️ Already notified for this article. Skipping.")
            results.append(DistributionResult(
                channel=channel.name,
                status="skipped",
                details={"reason": "Duplicate prevention"},
            ))
            continue

        try:
            result = channel.distribute(event)
            results.append(result)
            
            if not config.get("dry_run"):
                _record_history(db, slug, result)

                # Update analytics
                if channel.name == "push" and result.is_success:
                    analytics.record_push_sent(result.sent_count)
                    if result.failed_count > 0:
                        analytics.record_push_failed(result.failed_count)
                elif channel.name == "digest" and result.is_success:
                    analytics.record_digest_generated()
        except Exception as e:
            print(f"  ❌ Channel {channel.name} failed: {e}")
            result = DistributionResult(
                channel=channel.name,
                status="failed",
                error=str(e),
            )
            results.append(result)
            _record_history(db, slug, result)

    # 6. Print summary
    _print_summary(results)
    return True


def run_digest():
    """
    Send the daily digest.
    Called by the daily-digest GitHub Action cron.
    """
    print("\n" + "=" * 60)
    print("📬 MANTBYTE DAILY DIGEST")
    print("=" * 60)

    config = load_config()
    if getattr(args, 'dry_run', False):
        config['dry_run'] = True
        print("  🧪 DRY RUN MODE ENABLED - No real emails will be sent.\n")
    else:
        print("  ✅ Configuration loaded.\n")

    from distribution.channels.digest_channel import DigestChannel

    digest = DigestChannel(config)

    if not digest.is_enabled(config):
        print("  ⏭️ Digest channel is disabled. Exiting.")
        return True

    result = digest.send_digest()

    print(f"\n  {'─' * 40}")
    print(f"  Status: {result.status}")
    print(f"  Sent: {result.sent_count}")
    print(f"  Failed: {result.failed_count}")
    if result.error:
        print(f"  Error: {result.error}")
    print(f"  {'─' * 40}\n")

    return result.is_success


def run_test():
    """Run with a mock event for testing."""
    print("  🧪 Running in TEST mode with mock event.\n")

    mock_event = {
        "event": "article_published",
        "title": "Understanding AI-Generated CORS Vulnerabilities",
        "slug": "ai-generated-cors-vulnerabilities-test",
        "category": "Tech",
        "excerpt": "A deep dive into how AI code assistants can inadvertently introduce CORS misconfigurations.",
        "url": "/tech/2026/07/25/ai-generated-cors-vulnerabilities-test.html",
        "cover_image": "/assets/images/posts/default-cover.png",
        "tags": ["AI", "Security", "CORS"],
        "published_at": datetime.utcnow().isoformat(),
        "filename": "2026-07-25-ai-generated-cors-vulnerabilities-test.md",
    }

    # Keep test data outside the repository as well.
    with tempfile.TemporaryDirectory(prefix="mantbyte-distribution-test-") as temp_dir:
        event_path = os.path.join(temp_dir, "event.json")
        with open(event_path, "w", encoding="utf-8") as f:
            json.dump(mock_event, f, indent=2)
        run_distribution(event_path)


def validate_config():
    """Validate distribution configuration and secrets."""
    print("\n" + "=" * 60)
    print("🔍 VALIDATING DISTRIBUTION CONFIGURATION")
    print("=" * 60)
    config = load_config()
    
    issues = []
    
    # Check Firebase
    if config.get("enable_push") or config.get("enable_website_notifications") or config.get("enable_newsletter"):
        if not config.get("firebase_service_account"):
            issues.append("FIREBASE_SERVICE_ACCOUNT is missing but Firebase-dependent channels are enabled.")
        else:
            try:
                json.loads(config.get("firebase_service_account"))
                print("  ✅ FIREBASE_SERVICE_ACCOUNT is present and valid JSON.")
            except Exception:
                # Might be a file path, check if it exists
                if os.path.exists(config.get("firebase_service_account")):
                     print("  ✅ FIREBASE_SERVICE_ACCOUNT points to an existing file.")
                else:
                     issues.append("FIREBASE_SERVICE_ACCOUNT is not valid JSON and not a valid file path.")
    
    # Check SMTP
    if config.get("enable_email") or config.get("enable_digest"):
        if not config.get("smtp", {}).get("email") or not config.get("smtp", {}).get("password"):
            issues.append("SMTP_EMAIL or SMTP_PASSWORD (SMTP_APP_PASSWORD) is missing but email channels are enabled.")
        else:
            print("  ✅ SMTP credentials are present.")
            
    if issues:
        print("\n  ❌ Configuration issues found:")
        for issue in issues:
            print(f"    - {issue}")
        return False
        
    print("\n  ✅ All required configuration is valid.")
    return True


def run_verification():
    """
    Send verification emails to unverified subscribers.
    Called periodically.
    """
    print("\n" + "=" * 60)
    print("✉️  SENDING VERIFICATION EMAILS")
    print("=" * 60)
    
    config = load_config()
    if getattr(args, 'dry_run', False):
        config['dry_run'] = True
        print("  🧪 DRY RUN MODE ENABLED - No real emails will be sent.\n")
    
    if not config.get("enable_email_verification", True):
        print("  ⏭️ Email verification is disabled.")
        return True
        
    email_provider = config.get("email_provider")
    if not email_provider:
        print("  ❌ No EmailProvider configured. Cannot send verifications.")
        return False
        
    try:
        from distribution.channels.push_channel import get_firestore_db
        db = get_firestore_db(config)
    except Exception:
        db = None
        
    if not db:
        print("  ❌ Firestore not available. Cannot fetch unverified subscribers.")
        return False
        
    try:
        from distribution.email_verification import send_verification_email
        docs = db.collection("subscribers").where("verified", "==", False).get()
        
        sent_count = 0
        for doc in docs:
            data = doc.to_dict()
            if data.get("verification_sent"):
                continue # Already sent
                
            email = data.get("email")
            token = data.get("verification_token") or doc.id
            
            if email and token:
                if config.get("dry_run"):
                    print(f"  🧪 DRY RUN: Would have sent verification email to {email[:3]}***")
                    success = True
                else:
                    success = send_verification_email(
                        email=email,
                        token=token,
                        site_url=config.get("site_url", "https://mantbyte.github.io"),
                        email_provider=email_provider,
                        from_name=config.get("site_name", "Mantbyte")
                    )
                if success:
                    if not config.get("dry_run"):
                        doc.reference.update({
                            "verification_sent": True, 
                            "verification_sent_at": datetime.utcnow().isoformat()
                        })
                    sent_count += 1
                    
        if config.get("dry_run"):
            print(f"\n  ✅ 🧪 DRY RUN: Processed {sent_count} verification emails.")
        else:
            print(f"\n  ✅ Sent {sent_count} verification emails.")
        return True
    except Exception as e:
        print(f"  ❌ Failed to process verifications: {e}")
        return False


def _print_summary(results: list):
    """Print end-of-run summary."""
    print(f"\n{'=' * 60}")
    print("📊 DISTRIBUTION SUMMARY")
    print("=" * 60)

    for r in results:
        emoji = {"success": "✅", "partial": "⚠️", "failed": "❌", "skipped": "⏭️"}.get(r.status, "❓")
        line = f"  {emoji} {r.channel:15s} → {r.status}"
        if r.sent_count > 0:
            line += f" ({r.sent_count} sent)"
        if r.failed_count > 0:
            line += f" ({r.failed_count} failed)"
        if r.error:
            line += f" — {r.error[:50]}"
        print(line)

    print("=" * 60 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mantbyte Distribution Engine")
    parser.add_argument("--test", action="store_true", help="Run with mock event")
    parser.add_argument("--dry-run", action="store_true", help="Process without actually sending")
    parser.add_argument("--digest", action="store_true", help="Send daily digest")
    parser.add_argument("--verify", action="store_true", help="Send verification emails")
    parser.add_argument("--validate-config", action="store_true", help="Validate configuration and secrets")
    parser.add_argument("--event", type=str, help="Path to a temporary event JSON file")
    args = parser.parse_args()

    if args.validate_config:
        success = validate_config()
        sys.exit(0 if success else 1)
    elif args.verify:
        success = run_verification()
        sys.exit(0 if success else 1)
    elif args.test:
        run_test()
    elif args.digest:
        success = run_digest()
        sys.exit(0 if success else 1)
    else:
        if not args.event:
            parser.error("--event is required unless --test, --digest, --verify, or --validate-config is used")
        success = run_distribution(args.event)
        sys.exit(0 if success else 1)
