"""
Agent 11: GitHub Publishing Agent
Writes the article and image files to disk for the GitHub Actions PR step.
Also updates the knowledge base.
"""

import os
from agents.knowledge_base import add_article


def publish_article(
    markdown_content: str,
    filename: str,
    seo_data: dict,
    editorial_plan: dict,
    image_data: dict,
    review_result: dict,
    repo_root: str = None,
) -> dict:
    """
    Write the article file to disk (the GitHub Actions workflow handles the PR).
    
    Args:
        markdown_content: Complete Markdown file
        filename: Jekyll filename (e.g., 2026-07-24-slug.md)
        seo_data: SEO metadata
        editorial_plan: Editorial plan for the PR body
        image_data: Image paths
        review_result: Quality review result
        repo_root: Path to repository root
    
    Returns:
        Publishing result dict
    """
    if repo_root is None:
        repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    posts_dir = os.path.join(repo_root, "_posts")
    os.makedirs(posts_dir, exist_ok=True)

    # Write the Markdown file
    post_path = os.path.join(posts_dir, filename)
    with open(post_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)

    print(f"  📄 Article saved: _posts/{filename}")

    # Update knowledge base
    slug = seo_data.get("slug", filename.replace(".md", ""))
    title = editorial_plan.get("title", "")
    category = seo_data.get("category", "Tech")
    key_topics = seo_data.get("tags", [])

    # Construct the Jekyll URL
    date_parts = filename.split("-")[:3]
    cat_lower = category.lower()
    url = f"/{cat_lower}/{'/'.join(date_parts)}/{slug}.html"

    add_article(
        title=title,
        slug=slug,
        date="-".join(date_parts),
        category=category,
        key_topics=key_topics,
        url=url,
    )

    # Write PR body summary to a file (GitHub Actions will read it)
    pr_body = _build_pr_body(editorial_plan, seo_data, review_result, image_data)
    pr_body_path = os.path.join(repo_root, "_automation", "pr_body.md")
    with open(pr_body_path, "w", encoding="utf-8") as f:
        f.write(pr_body)

    print(f"  ✅ Publishing complete. Ready for PR creation.")

    return {
        "post_path": post_path,
        "filename": filename,
        "pr_body_path": pr_body_path,
        "success": True,
    }


def _build_pr_body(editorial_plan: dict, seo_data: dict, review_result: dict, image_data: dict) -> str:
    """Build the Pull Request description."""
    title = editorial_plan.get("title", "Unknown")
    score = review_result.get("score", "?")
    word_count = review_result.get("word_count", "?")
    category = seo_data.get("category", "?")
    tags = ", ".join(seo_data.get("tags", []))
    strengths = review_result.get("strengths", [])
    summary = review_result.get("summary", "")
    image_generated = image_data.get("generated", False)

    body = f"""## 🤖 AI-Generated Article

**Title:** {title}
**Category:** {category}
**Tags:** {tags}
**Word Count:** {word_count}
**Quality Score:** {score}/10
**Cover Image:** {'✅ Generated' if image_generated else '⚠️ Using default'}

---

### Quality Review Summary

{summary}

### Strengths
"""

    for s in strengths:
        body += f"- {s}\n"

    issues = review_result.get("issues", [])
    if issues:
        body += "\n### Issues Found\n"
        for issue in issues:
            severity = issue.get("severity", "info")
            emoji = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(severity, "⚪")
            body += f"- {emoji} [{severity}] {issue.get('description', '')}\n"

    body += "\n---\n\n> This article was automatically generated by the **Mantbyte AI Editorial Pipeline**.\n"
    body += "> Please review the content carefully before merging.\n"

    return body
